### PR TITLE
Add Spylive360

### PR DESCRIPTION
**Pull request by kpcyrd**

### CODE REVIEW

**Comment by kpcyrd** [comment]
I'm quite new to this, should `spylive360.com` be added as well? There are a few other subdomains that look like they might be used instead of s1 (although I haven't observed this in tests), like s2 and s3.

```
[sn0int][spylive360][kpcyrd/dns-resolve] > select subdomains where resolvable=1
#1, "mkt.spylive360.com"
	45.79.5.95
#2, "www.mkt.spylive360.com"
	45.79.5.95
#3, "mtc.spylive360.com"
	45.79.5.95
#4, "www.mtc.spylive360.com"
	45.79.5.95
#5, "ws.spylive360.com"
	104.225.221.146
#6, "spylive360.com"
	104.225.221.146
#7, "s3.spylive360.com"
	104.225.221.146
#8, "s2.spylive360.com"
	104.225.221.146
#9, "s1.spylive360.com"
	104.225.221.146
#10, "mtm.spylive360.com"
	104.225.221.146
#11, "metabase.spylive360.com"
	104.225.221.146
#12, "logs.spylive360.com"
	104.225.221.146
#13, "img.spylive360.com"
	104.225.221.146
#14, "db.spylive360.com"
	104.225.221.146
#15, "app.spylive360.com"
	104.225.221.146
#16, "blog.spylive360.com"
	45.79.5.95
#17, "www.blog.spylive360.com"
	45.79.5.95
#18, "mail.spylive360.com"
	45.79.5.95
#19, "www.spylive360.com"
	104.225.221.146
#20, "www.mtm.spylive360.com"
	45.79.5.95
#31, "ftp.spylive360.com"
	104.225.221.146
```

**Comment by Te-k** [comment]
In most cases, I have added only the domain used by the app to send data. If you have a doubt (like with s2 and s3), it is better to add them too (it is very unlikely to have false positive). I have added the main domain in most cases. So here, I would add `s2.spylive360.com`, `s3.spylive360.com` and `spylive360.com`.
I can do it directly to the repo if you are okay with that.

Would you have any sample of spylive360 to share?

**Comment by kpcyrd** [comment]
Sure, works for me!

During the install you're supposed to open `sl360.cc` (which only seems to redirect to `https://spylive360.com/download`) and the apk can be downloaded from `https://spylive360.com/apk`.

**Comment by Te-k** [comment]
Thanks, I just added them to the repository

**Pull request merged**
