### PR TITLE
IOCs for Cerberus, Bark, TalkLog, and OneMonitar

### PR DESCRIPTION
**Pull request by jcoscia**
Added 2 apps (Bark and OneMonitar) as well as IOCs for Cerberus and TalkLog. OneMonitar C2 was added to the Quad9 blocklist.

Also made a Yara rule for Cerberus. Currently just detects the main anti-theft app, and not their other products.

### CODE REVIEW

**Comment by Te-k** [comment]
Great work, thanks

**Comment by bbaros** [comment]
@jcoscia,  can you review addition of Bark to the list?  Bark is an app used for parents to provide safe experience for their children.  Unlike other child-monitoring apps, it doesn't track location involuntarily (children have to click a button to send it) and it doesn't provide access to all the content on the child's phone.  It monitors the phone content and uses filters and AI/ML to highlight potential issues which are then raised to parents for review.

Checkout https://www.bark.us/ for more info.

Please let me know if I can provide more info as a user of the app.  In my case, this affected me as I am using quad-9 DNS.

**Comment by jvoisin** [comment]
As stated on bark.us:

> While it is technically possible to set up Bark without your child's knowledge (assuming you have the log-in information for their online accounts), we highly encourage you to [discuss](https://www.bark.us/talk-to-kids/) your usage of Bark with your child. Talking to your child about alerts when they arise provides a good opportunity to have important conversations about serious topics.

This fits the [definition of stalkerware]( https://github.com/AssoEchap/stalkerware-indicators#whats-a-stalkerware ), thus we won't remove it.

**Comment by bbaros** [comment]
Thank you for the response @jvoisin, I understand your point of view.

Appreciate what you and your team are doing and I am thankful that there are people who care and work to make the world a better place. 

Regards
BB

**Pull request merged**
