### PR TITLE
new: Add MISP format exporter

### PR DESCRIPTION
**Pull request by Rafiot**
Just a script to generate a MISP Event from the IOCs in the repo (the script requires PyMISP from the main branch, it won't work with the latest package, as it needs a new object template).

### CODE REVIEW

**Comment by Rafiot** [comment]
If this issue https://github.com/Te-k/stalkerware-indicators/issues/2 can be solved, let me just re-create the initial MISP dump before merging.

**Comment by Te-k** [comment]
I have updated the appid file, do you want to recreate the MISP dump ?

**Comment by Rafiot** [comment]
Excellent, thank you!

And if you have new indicators (and as long as the format stays the same), you can run the script and it will update the event.

**Comment by Te-k** [comment]
Thanks !

**Pull request merged**
